"""Alembic configuration file."""
import os
from logging.config import fileConfig
from sqlalchemy import engine_from_config, pool

# this is the Alembic Config object, which provides
# the values of the [alembic] section of the .ini file, which can be
# accessed via the `config` object parameter in various functions within
# the script files.

config_file_path = os.path.dirname(__file__)
fileConfig(os.path.join(config_file_path, 'alembic.ini'))

# Alembic will not create migrations if the target_metadata is not set
# The migrations/env.py file will use this to generate migrations
